# Generated by Django 4.0.3 on 2022-03-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0002_nstimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_img', models.ImageField(upload_to='Emoji')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
